# Generated by Django 3.0.7 on 2020-06-11 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('original_title', models.CharField(max_length=100)),
                ('overview', models.CharField(max_length=10000)),
                ('genres', models.CharField(max_length=10000)),
                ('release_date', models.CharField(max_length=10)),
                ('runtime', models.CharField(max_length=4)),
                ('original_language', models.CharField(max_length=10000)),
                ('spoken_language', models.CharField(max_length=10000)),
                ('production_companies', models.CharField(max_length=10000)),
                ('production_countries', models.CharField(max_length=10000)),
                ('popularity', models.CharField(max_length=10)),
                ('tagline', models.CharField(max_length=500)),
                ('status', models.CharField(max_length=20)),
                ('homepage', models.CharField(max_length=100)),
            ],
        ),
    ]
